{"trial_id": "070", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_neurons_main", "default": null, "conditions": [], "min_value": 20, "max_value": 100, "step": 20, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers_main", "default": null, "conditions": [], "min_value": 2, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_neurons_int", "default": null, "conditions": [], "min_value": 20, "max_value": 200, "step": 20, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers_int", "default": null, "conditions": [], "min_value": 2, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_keypoints", "default": null, "conditions": [], "min_value": 20, "max_value": 100, "step": 20, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_vertices", "default": null, "conditions": [], "min_value": 2, "max_value": 30, "step": 4, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "lambd_mc", "default": 1e-06, "conditions": [], "min_value": 1e-06, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Float", "config": {"name": "pi_mc", "default": 1e-06, "conditions": [], "min_value": 1e-06, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Float", "config": {"name": "smoothness_reg", "default": 1e-06, "conditions": [], "min_value": 1e-06, "max_value": 0.1, "step": null, "sampling": "log"}}], "values": {"num_neurons_main": 40, "num_layers_main": 3, "num_neurons_int": 80, "num_layers_int": 10, "num_keypoints": 40, "num_vertices": 14, "lambd_mc": 0.01, "pi_mc": 0.01, "smoothness_reg": 1e-06}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/tupho/miniconda3/envs/keras2/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node ArithmeticOptimizer/AddOpsRewrite_AddN_1 defined at (most recent call last):\n<stack traces unavailable>\nInputs to operation ArithmeticOptimizer/AddOpsRewrite_AddN_1 of type AddN must have the same size and shape.  Input 0: [] != input 10: [0]\n\t [[{{node ArithmeticOptimizer/AddOpsRewrite_AddN_1}}]] [Op:__inference_test_function_2048028]\n"}